use wlbase_dev;
CREATE  TABLE  if not exists t_qqweibo_user_info(
id String,
certificationInfo String,
faceUrl String,
gender String,
isVIP String,
isWbStar String,
auth String,
nickName String,
occupation String,
personal String,
regTime String,
h_nation String,
h_countryName String,
h_province_ String,
h_provinceName String,
h_city String,
h_cityName String,
l_nation String,
l_countryName String,
l_province_ String,
l_provinceName String,
l_city String,
l_cityName String,
tags_r String,
b_year String,
b_month String,
b_day String,
b_star String,
com_startYear1 String,
com_endYear1 String,
com_comName1 String,
com_depName1 String,
com_startYear2 String,
com_endYear2 String,
com_comName2 String,
com_depName2 String,
com_startYear3 String,
com_endYear3 String,
com_comName3 String,
com_depName3 String,
year1 String,
background1 String,
school1 String,
department1 String,
year2 String,
background2 String,
school2 String,
department2 String,
year3 String,
background3 String,
school3 String,
department3 String
)
COMMENT '电商品牌标签等级表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001'   LINES TERMINATED BY '\n'
stored as textfile ;


alter table t_qqweibo_user_info
replace columns
(
id String COMMENT '微博id',
certificationInfo String COMMENT '认证信息',
faceUrl String COMMENT '头像url',
gender String COMMENT '性别，0未知，1男，2女',
isVIP String COMMENT '微博vip？',
isWbStar String COMMENT '微博之星',
auth String COMMENT '微博认证等级 ，1是个人，2是机构',
nickName String COMMENT '昵称',
occupation String COMMENT '职业',
personal String COMMENT '个人简介',
regTime String COMMENT '注册时间',
h_nation String COMMENT '家乡国家id',
h_countryName String COMMENT '家乡国家名称',
h_province_ String COMMENT '家乡省份id',
h_provinceName String COMMENT '家乡省份名称',
h_city String COMMENT '家乡城市id',
h_cityName String COMMENT '家乡城市名称',
l_nation String COMMENT '现居地国家id',
l_countryName String COMMENT '现居地国家名称',
l_province_ String COMMENT '现居地省份id',
l_provinceName String COMMENT '现居地省份名称',
l_city String COMMENT '现居地城市id',
l_cityName String COMMENT '现居地城市名称',
tags_r String COMMENT '标签信息',
b_year String COMMENT '出生年份',
b_month String COMMENT '出生月份',
b_day String COMMENT '出生日子',
b_star String COMMENT '出生星座',
com_startYear1 String COMMENT '公司1入职年份',
com_endYear1 String COMMENT '公司1离职年份',
com_comName1 String COMMENT '公司1名称',
com_depName1 String COMMENT '公司1职位',
com_startYear2 String COMMENT '公司2入职年份',
com_endYear2 String COMMENT '公司2离职年份',
com_comName2 String COMMENT '公司2名称',
com_depName2 String COMMENT '公司2职位',
com_startYear3 String COMMENT '公司3入职年份',
com_endYear3 String COMMENT '公司3离职年份',
com_comName3 String COMMENT '公司3名称',
com_depName3 String COMMENT '公司3职位',
year1 String COMMENT '学校1入学年份',
background1 String COMMENT '学校1性质',
school1 String COMMENT '学校1名称',
department1 String COMMENT '学校1学院',
year2 String COMMENT '学校2入学年份',
background2 String COMMENT '学校2性质',
school2 String COMMENT '学校2名称',
department2 String COMMENT '学校2入学年份',
year3 String COMMENT '学校3入学年份',
background3 String COMMENT '学校3性质',
school3 String COMMENT '学校3名称',
department3 String COMMENT '学校3入学年份'
);

alter table t_qqweibo_user_info set TBLPROPERTIES('comment' = '腾讯微博用户信息表');